name: test
on:
  workflow_dispatch:
jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl wget

      - name: Get latest release info
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/releases/latest"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          # 获取 Release 详情
          RELEASE_INFO=$(curl -s -H "Authorization: Bearer ${TOKEN}" "${URL}")
          
          # 输出 Release JSON 供调试
          echo "Release JSON:"
          echo "$RELEASE_INFO" | jq .

          # 获取 frpc 和 frpc.toml 下载链接
          FRPC_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | startswith("frpcc")) | .browser_download_url')
          echo $FRPC_URL
            

          
     
