name: ubuntu-2404-arm64

on:
  workflow_dispatch:
  
jobs:
  job1:
    uses: ./.github/workflows/share_ubuntu.yml
    with:
        runs-on: ubuntu-24.04-arm
    secrets: 
      CUSTOM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      WX_PUSH_APP_TOKEN: ${{ secrets.WX_PUSH_APP_TOKEN }}
      WX_UID: ${{ secrets.WX_UID }}
      CYM_TOKEN: ${{ secrets.CYM_TOKEN }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      REMOTE_PORT: ${{ secrets.UBUNTU_REMOTE_PORT }}
